config/routes.rb
Rails.application.routes.draw do

  resources :posts # To all the routes for the posts controller

  # get 'posts/index'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/edit'
  # get 'posts/update'
  # get 'posts/destroy'

  get 'register', to: 'auth#signup_form', as: 'register'
  post 'signup', to: 'auth#signup', as: 'signup'
  post 'signin', to: 'auth#signin', as: 'signin'
  get 'login', to: 'auth#signin_form', as: 'login'
  post 'logout', to: 'auth#logout', as: 'logout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, :content, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true , format: {with: /\A[a-zA-Z]+\z/, message: "only allows letters"}#, allows nil: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true, length: {minimum: 6}

    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticated_user
        return redirect_to root_path if session[:user_id]
    end

    def unauthenticated_user
        return redirect_to login_path unless session[:user_id]
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticated_user, except: [:logout]


  def signup_form
    @user = User.new
  end

  def signup

    @user  = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))

    @user.valid? # => check if the user is valid
    # puts @user.errors

    puts "---------------------"
    # convert user erros to json
    puts @user.errors[:name]
    puts "---------------------"

    return redirect_to root_path if @user.save 

    render 'auth/signup_form'

    # redirect_back fallback_location: register_auth

  end

  def signin
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      return redirect_to root_path
    end
    redirect_back fallback_location: login_path
  end

  def signin_form
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :unauthenticated_user
  before_action :user_object, only: [:index, :create]


  def index
    @posts = @user.posts
  end
  
  def new
    @post = Post.new
  end

  def create
  #  @post = Post.new(params.require(:post).permit(:title, :content)) 
   
  #  @post.user_id = session[:user_id]
  
   @post = @user.posts.create(post_params)

   @post.valid?

    # return redirect_to posts_path, notice: 'Post was created' if @post.save
    return redirect_to posts_path, notice: 'Post was created' if @post.persisted?


    render 'posts/new'
   
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update

    post = Post.find(params[:id])
    post.update(post_params)
    
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def user_object
    @user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% unless session[:user_id] %>
        <li class="nav-item">
          <%= link_to 'Register', register_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= button_to 'Logout', logout_path, method: :post, class: 'nav-link border-0 bg-transparent' %>
        </li>
      <% end %>

      <% if session[:user_id] %>

      <li class="nav-item">
      <%= link_to 'Posts', posts_url , class: 'nav-link border-0 bg-transparent' %>

      <li class="nav-item">
      <%= link_to 'New', new_post_url, class: 'nav-link border-0 bg-transparent' %>
    </li>
      <% end %>


        </ul>


    </div>
  </div>
</nav>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>
    <div class="mb-3">
    <%= f.text_field 'title', class: 'form-control', placeholder: 'Title...' %>
    <span class="text-danger"> <%= @post.errors[:title][0] %></span>
    </div>
    <div class="mb-3">
    <%= f.text_area 'content', class: 'form-control', placeholder: 'content...' %>
    <span class="text-danger"> <%= @post.errors[:content][0] %></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
        <%= flash[:notice] %>
    </div>
<% end %>


<div class="d-flex flex-wrap">
<% @posts.each do |post| %>
    <div class="card m-2" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <%= link_to 'Edit', edit_post_path(@post, :id => post.id), class: 'nav-link border-0 bg-transparent' %>

        <%= button_to 'Delete', post_path(post.id), method: :delete, class: ' border-0 bg-transparent' %>

    </div>
  </div>

<% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>